export interface Standings{
    TeamID: number,
    Season: number,
    Wins: number | null,
    Losses: number | null,
    Percentage: number | null,
    ConferenceWins: number | null,
    ConferenceLosses: number | null,
    DivisionWins: number | null,
    DivisionLosses: number | null,
    HomeWins: number | null,
    HomeLosses: number | null,
    AwayWins: number | null,
    AwayLosses: number | null,
    LastTenWins: number | null,
    LastTenLosses: number | null,
    PointsPerGameFor: number | null,
    PointsPerGameAgainst: number | null,
    Streak: number | null,
    GamesBack: number | null,
    ConferenceRank: number | null,
    DivisionRank: number | null
};

export const templateStandings: Standings = {
    Season: 0,
    TeamID: 0,
    Wins: null,
    Losses: null,
    Percentage: null,
    ConferenceWins: null,
    ConferenceLosses: null,
    DivisionWins: null,
    DivisionLosses: null,
    HomeWins: null,
    HomeLosses: null,
    AwayWins: null,
    AwayLosses: null,
    LastTenWins: null,
    LastTenLosses: null,
    PointsPerGameFor: null,
    PointsPerGameAgainst: null,
    Streak: null,
    GamesBack: null,
    ConferenceRank: null,
    DivisionRank: null
};